#!/bin/bash
set -euo pipefail

# Bridges Remote Desktop — Xtigervnc + XFCE wrapper
# Starts Xtigervnc on :1 with no VNC auth (portal JWT handles auth)
# Then launches XFCE desktop as bridgesrd user

DISPLAY_NUM=:1
VNC_PORT=5901
GEOMETRY=1280x1024
DEPTH=24
RD_USER=bridgesrd
XDG_DIR="/tmp/bridges-rd-runtime"
LOG_DIR="/var/log/bridges-rd"
ENV_FILE="/home/$RD_USER/.bridges-rd-env"
XAUTHORITY_FILE="/home/$RD_USER/.Xauthority"
SESSION_GUARD="/usr/local/bin/bridges-rd-session-guard.sh"
VNC_PID=""
XFCE_PID=""

# A login-shell `su -` opens a pam_systemd session and moves the child out of
# this service's control group. Repeated service restarts then strand desktop
# helpers (and login-shell ssh-agents) in abandoned session scopes. Keep every
# desktop child in bridges-rd-xtigervnc.service so KillMode=control-group owns
# its complete lifetime.
run_as_rd() {
  /usr/bin/setpriv \
    --reuid="$RD_USER" \
    --regid="$RD_USER" \
    --init-groups \
    --pdeathsig=TERM \
    -- /usr/bin/env -i \
    HOME="/home/$RD_USER" \
    USER="$RD_USER" \
    LOGNAME="$RD_USER" \
    SHELL=/bin/bash \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG="${LANG:-C.UTF-8}" \
    "$@"
}

cleanup() {
  local pid
  for pid in "$XFCE_PID" "$VNC_PID"; do
    if [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
    fi
  done
}
trap cleanup EXIT INT TERM

if [[ ! -x "$SESSION_GUARD" ]]; then
  echo "Remote Desktop session guard is missing: $SESSION_GUARD" >&2
  exit 1
fi

# Refuse to unlink a live display owned by an unknown or legacy process. The
# guard removes only stale :1 locks after proving their recorded owner is gone.
"$SESSION_GUARD" prepare

# Create log directory (not in /tmp, avoids protected_regular issues)
mkdir -p "$LOG_DIR"
chown "$RD_USER:$RD_USER" "$LOG_DIR"

# Clean up stale Xvfb/display :99 remnants
rm -f /tmp/.X99-lock /tmp/.X11-unix/X99 2>/dev/null || true
pkill -u "$RD_USER" -f "Xvfb" 2>/dev/null || true

# Kill any leftover XFCE sessions from this user before starting fresh
pkill -u "$RD_USER" -f "xfce4-session" 2>/dev/null || true

# Clear stale XFCE geometry/session state before bringing the desktop back.
rm -rf /home/"$RD_USER"/.cache/sessions/* 2>/dev/null || true

# Ensure XDG_RUNTIME_DIR exists for the desktop user
mkdir -p "$XDG_DIR"
chown "$RD_USER:$RD_USER" "$XDG_DIR"
chmod 700 "$XDG_DIR"

cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by BridgesLLM VNC launcher — do not edit manually.
export DISPLAY=$DISPLAY_NUM
export XAUTHORITY=$XAUTHORITY_FILE
export XDG_RUNTIME_DIR=$XDG_DIR
export PULSE_SERVER=unix:$XDG_DIR/pulse/native
export SDL_AUDIODRIVER=pulseaudio
export DEBIAN_FRONTEND=noninteractive
ENVEOF
chown "$RD_USER:$RD_USER" "$ENV_FILE"
chmod 0640 "$ENV_FILE"

# Authenticate local X11 clients instead of disabling X access control. This
# prevents unrelated host processes from attaching to the operator desktop.
install -o "$RD_USER" -g "$RD_USER" -m 0600 /dev/null "$XAUTHORITY_FILE"
XAUTH_COOKIE="$(mcookie)"
run_as_rd xauth -f "$XAUTHORITY_FILE" add "$DISPLAY_NUM" . "$XAUTH_COOKIE"

# Start Xtigervnc as root (it manages its own display)
/usr/bin/Xtigervnc "$DISPLAY_NUM" \
  -UseBlacklist=0 \
  -localhost=1 \
  -AcceptSetDesktopSize=1 \
  -desktop "BridgesLLM Remote Desktop" \
  -rfbport "$VNC_PORT" \
  -SecurityTypes None \
  -geometry "$GEOMETRY" \
  -depth "$DEPTH" \
  -auth "$XAUTHORITY_FILE" &

VNC_PID=$!

# Wait for the display to become available
DISPLAY_READY=false
for i in $(seq 1 20); do
  if DISPLAY="$DISPLAY_NUM" XAUTHORITY="$XAUTHORITY_FILE" xdpyinfo >/dev/null 2>&1; then
    echo "Display $DISPLAY_NUM is ready (attempt $i)"
    DISPLAY_READY=true
    break
  fi
  sleep 0.5
done
if [[ "$DISPLAY_READY" != "true" ]]; then
  echo "Display $DISPLAY_NUM did not become responsive" >&2
  exit 1
fi

# Start PulseAudio for audio support (virtual null sink → browser WebSocket)
run_as_rd XDG_RUNTIME_DIR="$XDG_DIR" LOG_DIR="$LOG_DIR" /bin/bash -c '
  # Kill stale PulseAudio
  pulseaudio --kill 2>/dev/null || true
  sleep 0.5
  # Retry cold boots while the per-user runtime directory settles.
  for attempt in 1 2 3 4 5; do
    if pulseaudio --start --exit-idle-time=-1 2>>"$LOG_DIR/pulseaudio.log"; then
      echo "PulseAudio started on attempt $attempt"
      break
    fi
    echo "PulseAudio start failed (attempt $attempt), retrying..." >>"$LOG_DIR/pulseaudio.log"
    sleep 2
  done
  sleep 1
  # Configure for audio streaming
  export PULSE_SERVER="unix:$XDG_RUNTIME_DIR/pulse/native"
  pactl set-default-sink auto_null 2>/dev/null || true
  # CRITICAL: Unload suspend-on-idle so the monitor source always streams
  # Without this, parec blocks when no audio is playing and the browser gets no data
  pactl unload-module module-suspend-on-idle 2>/dev/null || true
  echo "PulseAudio started (suspend-on-idle disabled)"
' &
PA_PID=$!
wait $PA_PID 2>/dev/null || true
echo "PulseAudio initialized"

# Start XFCE as bridgesrd user on display :1
# Redirect inside the unprivileged shell to keep every log write user-owned.
run_as_rd \
  DISPLAY="$DISPLAY_NUM" \
  XAUTHORITY="$XAUTHORITY_FILE" \
  XDG_RUNTIME_DIR="$XDG_DIR" \
  PULSE_SERVER="unix:$XDG_DIR/pulse/native" \
  LOG_DIR="$LOG_DIR" \
  /bin/bash -c 'exec dbus-launch --exit-with-session startxfce4 >>"$LOG_DIR/xfce.log" 2>&1' &

XFCE_PID=$!
echo "Xtigervnc PID=$VNC_PID, XFCE PID=$XFCE_PID"

# Do not report this service ready merely because the RFB socket exists. Wait
# for the real XFCE session and repair harmless idle/locker drift while XFCE's
# delayed autostart phase settles.
SESSION_READY=false
for i in $(seq 1 40); do
  "$SESSION_GUARD" repair >/dev/null 2>&1 || true
  if "$SESSION_GUARD" check >/dev/null 2>&1; then
    SESSION_READY=true
    echo "XFCE session is ready (attempt $i)"
    break
  fi
  if ! kill -0 "$XFCE_PID" 2>/dev/null; then
    echo "XFCE exited before becoming ready" >&2
    exit 1
  fi
  sleep 0.5
done
if [[ "$SESSION_READY" != "true" ]]; then
  echo "XFCE session did not satisfy the semantic health policy" >&2
  exit 1
fi

# Keep the VNC cut-text and X11 selections synchronized when vncconfig is
# available. The Portal HTTP clipboard bridge remains the reliable fallback.
if command -v vncconfig >/dev/null 2>&1; then
  (
    while kill -0 "$VNC_PID" 2>/dev/null; do
      run_as_rd DISPLAY="$DISPLAY_NUM" XAUTHORITY="$XAUTHORITY_FILE" \
        vncconfig -nowin >>$LOG_DIR/vncconfig.log 2>&1 || true
      sleep 5
    done
  ) &
  echo "Clipboard bridge (vncconfig) started"
else
  echo "vncconfig not found; VNC clipboard bridge disabled"
fi

if [ -x /usr/local/bin/bridges-rd-window-fit.sh ]; then
  run_as_rd DISPLAY="$DISPLAY_NUM" XAUTHORITY="$XAUTHORITY_FILE" \
    /usr/local/bin/bridges-rd-window-fit.sh >>$LOG_DIR/window-fit.log 2>&1 &
  echo "Window-fit watcher started"
fi

# Report ready only after semantic XFCE convergence, then replace this launcher
# with the guard. Keeping readiness and watchdog heartbeats on the systemd main
# PID lets NotifyAccess=main reject Xtigervnc's own premature READY=1.
systemd-notify --pid=parent --ready --status='Remote Desktop session ready'
echo "Session guard taking over systemd main PID=$$"
exec "$SESSION_GUARD" watch "$VNC_PID" "$XFCE_PID"
